"""Add courses and tasks tables

Revision ID: 151ec29bd1b6
Revises: fe6b70278593
Create Date: 2026-02-10 04:13:41.540845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '151ec29bd1b6'
down_revision: Union[str, None] = 'fe6b70278593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
