"""add_task_logs_reflexion_logs_and_profile_fields

Revision ID: 5f35b9bff03b
Revises: a87adc826289
Create Date: 2026-03-10 21:44:46.340162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f35b9bff03b'
down_revision: Union[str, None] = 'a87adc826289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reflexion_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('updated_traits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reflexion_trigger', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reflexion_logs_id'), 'reflexion_logs', ['id'], unique=False)
    op.create_table('task_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('actual_duration_mins', sa.Integer(), nullable=False),
    sa.Column('drain_intensity', sa.Integer(), nullable=False),
    sa.Column('mood_note', sa.Text(), nullable=True),
    sa.Column('completion_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_block', sa.String(length=20), nullable=False),
    sa.Column('was_on_time', sa.Boolean(), nullable=False),
    sa.Column('delay_mins', sa.Integer(), nullable=False),
    sa.Column('duration_ratio', sa.Float(), nullable=False),
    sa.Column('ai_feedback_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('drain_intensity >= 1 AND drain_intensity <= 10', name='ck_drain_intensity_range'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_index(op.f('ix_task_logs_id'), 'task_logs', ['id'], unique=False)
    op.add_column('user_profiles', sa.Column('last_reflexion_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_profiles', sa.Column('persona_confidence', sa.Float(), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'persona_confidence')
    op.drop_column('user_profiles', 'last_reflexion_at')
    op.drop_index(op.f('ix_task_logs_id'), table_name='task_logs')
    op.drop_table('task_logs')
    op.drop_index(op.f('ix_reflexion_logs_id'), table_name='reflexion_logs')
    op.drop_table('reflexion_logs')
    # ### end Alembic commands ###
