"""add_google_event_id_to_tasks

Revision ID: 6f2e5a7bc290
Revises: ea044ed96245
Create Date: 2026-02-17 23:29:12.726924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f2e5a7bc290'
down_revision: Union[str, None] = 'ea044ed96245'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('google_event_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'google_event_id')
    # ### end Alembic commands ###
