"""add_timezone_to_user_profile

Revision ID: a87adc826289
Revises: 6f2e5a7bc290
Create Date: 2026-02-18 01:53:22.880441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a87adc826289'
down_revision: Union[str, None] = '6f2e5a7bc290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('timezone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'timezone')
    # ### end Alembic commands ###
