"""add_code_and_term_to_courses

Revision ID: ea044ed96245
Revises: e8a055fd4212
Create Date: 2026-02-17 04:17:06.926515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea044ed96245'
down_revision: Union[str, None] = 'e8a055fd4212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('code', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('term', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'term')
    op.drop_column('courses', 'code')
    # ### end Alembic commands ###
